#!/bin/bash

node r.js -o app.build.js
rm public_html_optimized/build.txt #clean up build log
rm public_html_optimized/css/fonts.css #remove unused css generated by IDE
rm -rf public_html_optimized/less #remove less source code
#java -classpath js.jar:compiler.jar org.mozilla.javascript.tools.shell.Main r.js -o app.build.js