INSERT INTO `gameNames` (`gameid`, `name`) VALUES
('GB_BOXES', 'Boxes'),
('GBC_JETPAKDX', 'Jet Pak DX'),
('SGB_POKEMON BLUE', 'Pokemon Blue Version'),
('SGB_POKEMON RED', 'Pokemon Red Version'),
('GBC_PM_CRYSTAL', 'Pokemon Crystal Version'),
('SGBC_POKEMON YELLOW', 'Pokemon Yellow Version'),
('SGBC_POKEMON_GLDAAUE', 'Pokemon Gold Version'),
('SGBC_POKEMON_SLVAAXE', 'Pokemon Silver Version'),
('SGBC_POKECARD', 'Pokemon Trading Card Game'),
('GBC_1942', '1942'),
('GB_SIMPSON ESCAPE', 'Bart Simpson''s Escape From Camp Deadly'),
('GBC_KLONDIKE', 'Klondike'),
('GBC_MAZEZAM', 'MazezaM'),
('GBC_MINES', 'Mines'),
('GBC_NIBBLES BY SACK', 'Nibbler'),
('GBC_OYOYO', 'Oyoyo'),
('GBC_PACMAN', 'Pakman'),
('GBC_PAKUS', 'Pakus'),
('GBC_PAZEEK', 'PaZeek'),
('GBC_QBERT', 'Q*Bert'),
('GBC_SIMON', 'Simon Clone'),
('GB_FISHER', 'Starfisher'),
('GBC_BUST A MOVEAA4E', 'Bust-A-Move 4'),
('GBC_RAMPAGE WT', 'Rampage: World Tour'),
('GBC_RAMPAGE UT AUTE', 'Rampage: Universal Tour'),
('SGBC_TETRIS DX', 'Tetris DX'),
('GB_KIRBY DREAM LAND', 'Kirby''s Dream Land'),
('SGB_KIRBY2', 'Kirby''s Dream Land 2'),
('SGBC_ZELDA', 'The Legend of Zelda: Link''s Awakening DX'),
('GB_SUPER MARIOLAND', 'Super Mario Land'),
('GB_MARIOLAND2', 'Super Mario Land 2: 6 Golden Coins'),
('GB_METROID2', 'Metroid II: Return of Samus'),
('GB_SUPERMARIOLAND3', 'Wario Land: Super Mario Land 3'),
('SGB_MARIO''S PICROSS', 'Mario''s Picross'),
('GBC_DK COUNTRY', 'Donkey Kong Country'),
('GB_TETRIS', 'Tetris'),
('GBC_ZELDA NAYRUAZ8E', 'The Legend of Zelda: Oracle of Ages'),
('GBC_ZELDA DIN', 'The Legend of Zelda: Oracle of Seasons'),
('GBC_MARIO DELUXAHYE', 'Super Mario Bros. Deluxe'),
('GBC_TOKI TORI', 'Toki Tori'),
('GBC_Maze B', 'Tyrannosaurus Tex'),
('SGB_GAMEBOYCAMERA', 'Gameboy Camera'),
('SGB_BOMBER MAN GB', 'Bomberman GB'),
('GB_BOY AND BLOB GB1', 'A Boy and His Blob: Rescue of Princess Blobette '),
('GBC_CROC 2', 'Croc 2'),
('GBC_CGBTENNIS', 'Mario Tennis'),
('GBC_WARLOCKED', 'Warlocked'),
('SGB_WARIOLAND2', 'Wario Land II'),
('SGBC_CGBWARIOLAND2', 'Wario Land II'),
('GBC_WARIOLAND3', 'Wario Land 3'),
('GBC_RAYMAN', 'Rayman'),
('GBC_POKEMONPC', 'Pokemon Puzzle Challenge'),
('GBC_MARIO GOLF', 'Mario Golf'),
('GB_KID ICARUS', 'Kid Icarus'),
('SGB_STREET FIGHTER 2', 'Street Fighter 2'),
('SGB_DONKEYKONGLAND95', 'Donkey Kong Land'),
('SGB_DONKEYKONGLAND 2', 'Donkey Kong Land 2'),
('SGB_DONKEYKONGLAND 3', 'Donkey Kong Land 3'),
('GB_DR.MARIO', 'Dr. Mario'),
('GB_FACEBALL 2000', 'Faceball 2000'),
('GBC_PROJECTS11', 'Project S-11'),
('GB_MEGAMAN', 'Megaman: Dr. Willy''s Revenge'),
('GB_MEGA MAN 2', 'Megaman II'),
('GB_MEGAMAN3', 'Megaman III'),
('GB_MEGAMAN4', 'Megaman IV'),
('SGB_MEGAMAN5', 'Megaman V'),
('GBC_MEGAMAN X', 'Megaman Xtreme'),
('GBC_MEGAMANX2SEB2XE', 'Megaman Xtreme 2'),
('GBC_BUGS BUNNY', 'Looney Tunes: Carrot Crazy'),
('GBC_BUGS BUNNY4AO4E', 'Bugs Bunny in Crazy Castle 4'),
('GBC_BUGSBUNNY CC3', 'Bugs Bunny: Crazy Castle 3'),
('GBC_CANNON FODDBCFE', 'Cannon Fodder'),
('GBC_CGB DEMO', 'Gameboy Color Promotional Demo'),
('GBC_CROC', 'Croc: Legend of the Gobbos'),
('GBC_GPS BOY', 'GPS Boy'),
('GBC_HARRYPOTTERBHVE', 'Harry Potter and the Sorcerer''s Stone'),
('GBC_HPCOSECRETSBH6E', 'Harry Potter and the Chamber of Secrets'),
('GBC_LT RACING', 'Looney Tunes Racing'),
('GBC_TG POCKET2', 'Top Gear Pocket 2'),
('GBC_TOPGEAR POCKET', 'Top Gear Pocket'),
('GBC_TOPGUN', 'Top Gun: Firestorm'),
('GBC_TYCORAT1', 'Tyco R/C Racin'' Ratz'),
('SGBC_DRAGON WMONAWQE', 'Dragon Warrior Monsters'),
('SGBC_MONOPOLYGB', 'DX Monopoly GB'),
('SGBC_TOYSTORY 2', 'Toy Story 2'),
('SGBC_POKEPINBALLVPHE', 'Pokemon Pinball'),
('GB_AEROSTAR', 'Aerostar'),
('GB_BUGS BUNNY', 'The Bugs Bunny Crazy Castle'),
('GB_BUGSCRAZYCASTLE2', 'The Bugs Bunny Crazy Castle 2'),
('GB_CASTLEVANIA ADVE', 'The Castlevania Adventure'),
('GB_CASTLEVANIA2 BEL', 'Castlevania II: Belmont''s Revenge'),
('GB_DIABLO', 'Diablo'),
('GB_DICK TRACY', 'Dick Tracy'),
('GB_DIG DUG', 'Dig Dug'),
('GB_FLIPULL', 'Flipull'),
('GB_GO GO TANK', 'Go! Go! Tank'),
('GB_GREMLINS 2', 'Gremlins 2: The New Batch'),
('GB_KID DRACULA', 'Kid Dracula'),
('GB_LOONEY TUNES', 'Looney Tunes'),
('GB_LOOPZ', 'Loopz'),
('GB_LUNA LANDER', 'Lunar Lander'),
('GB_MARU''S MISSION', 'Maru''s Mission'),
('GB_MYSTERIUM', 'Mysterium'),
('GB_NORTH STAR', 'Fist of the North Star'),
('GB_PIPE DREAM', 'Pipe Dream'),
('GB_Q*BERT II', 'Q*bert'),
('GB_QBILLION', 'QBillion'),
('GB_QUARTH', 'Quarth'),
('GB_ROBOCOP', 'RoboCop'),
('GB_ROBOCOP2', 'RoboCop 2'),
('GB_RTYPE', 'R-Type'),
('GB_RTYPE 2', 'R-Type II'),
('GB_RUNES OF VIRTUE', 'Ultima: Runes of Virtue'),
('GB_RUNES OF VIRTUE2', 'Ultima: Runes of Virtue II'),
('GB_THE PUNISHER', 'The Punisher'),
('GB_TOPGUN 2', 'Top Gun: Guts and Glory'),
('GB_TOXIC CRUSADERS', 'Toxic Crusaders'),
('GB_ZELDA', 'The Legend of Zelda: Link''s Awakening'),
('SGB_BOMBER MAN GB 2', 'Bomberman GB 2'),
('SGB_BOMBERMAN GB3', 'Bomberman GB 3'),
('SGB_BOMCOL', 'Bomberman Collection'),
('SGB_CASTLEVANIA', 'Castlevania: Legends'),
('SGB_GAMEBOYCAMERA G', 'Gameboy Camera Gold'),
('SGB_TETRIS ATTACK', 'Tetris Attack'),
('SGB_TETRIS BLAST', 'Tetris Blast'),
('SGB_TETRIS2', 'Tetris 2'),
('SGB_TETRIS PLUS', 'Tetris Plus'),
('SGB_TOY STORY', 'Toy Story'),
('GBC_10-PIN BOWLVP9E', '10-Pin Bowling'),
('GBC_3DPOCKTPOOLBVPP', '3-D Pocket Pool'),
('GBC_4X4 WORLD TAQ3P', '4x4 World Trophy'),
('GBC_ALONEINTHEDBIDE', 'Alone in the Dark: The New Nightmare'),
('GBC_AM SFBX', 'Action Man: Search for Base X'),
('GBC_BARBIEPETREBPEE', 'Barbie Pet Rescue'),
('GBC_BOB THE BUIBOBE', 'Bob the Builder'),
('GBC_CARMAGEDDONAKWP', 'Carmageddon'),
('GBC_CATZ       AZCE', 'Catz'),
('GBC_DALMATIANS', '102 Dalmatians: Puppies to the Rescue'),
('GBC_DEMOTRONIC 100%', 'Demotronic'),
('GBC_DOGZ       AOZE', 'Dogz'),
('GBC_DRAGONLAIR', 'Dragon''s Lair'),
('GBC_F1 RACING CAEQP', 'F-1 Racing Championship'),
('GBC_FORCE21 GBCBFCE', 'Force 21'),
('GBC_GODZILLA-TSBGDE', 'Godzilla: The Series - Monster Wars'),
('GBC_GRAND THEFTAOAE', 'Grand Theft Auto'),
('GBC_GREMLINS', 'Gremlins Unleashed'),
('GBC_GTA 2', 'Grand Theft Auto 2'),
('GBC_LEGO RACERSBLRP', 'Lego Racers'),
('GBC_MILLIONAIREBMOE', 'Who Wants to be a Millionaire?'),
('GBC_OTTIFANTEN', 'Ottifanten'),
('GBC_PNBALFRENZYVM2E', 'Pinball Frenzy'),
('GBC_Q*BERT', 'Q*Bert'),
('GBC_R-TYPE DX', 'R-Type DX'),
('GBC_SBSP LOTLS!BQPE', 'SpongeBob SquarePants: The Legend of the Lost Spatula'),
('GBC_SCOOBY DOO', 'Scooby Doo! Classic Creep Capers'),
('GBC_SCRABBLE', 'Scrabble'),
('GBC_SHANTAE', 'Shantae'),
('GBC_SPIDER-MAN!BSEE', 'Spider-Man'),
('GBC_SPIDERMAN2', 'Spider-Man 2: The Sinister Six'),
('GBC_THRILLRIDE!VUPE', '3-D Ultra Pinball: Thrillride'),
('GBC_TOMB RAIDERAT9E', 'Tomb Raider'),
('GBC_TOMBRAIDER2B9TE', 'Tomb Raider: Curse of the Sword'),
('GBC_TONYHAWK''S2BTGE', 'Tony Hawk''s Pro Skater 2'),
('GBC_TONYHAWK''SPBTFE', 'Tony Hawk''s Pro Skater'),
('GBC_TONYHAWKPS3B3TE', 'Tony Hawk''s Pro Skater 3'),
('GBC_TOYSTORYRA', 'Toy Story Racer'),
('GBC_TWINE CGB', 'The World Is Not Enough'),
('GBC_WENDY', 'Wendy: Every Witch Way'),
('SGBC_BUGS LIFE', 'Bug''s Life'),
('GB_GODZILLA', 'Godzilla'),
('GB_NOOBOW', 'Noobow'),
('GB_SPIDER-MAN', 'The Amazing Spider-Man'),
('GB_SPIDER-MAN 2', 'The Amazing Spider-Man 2'),
('GB_SPIDER-MAN 3 DMG', 'The Amazing Spider-Man 3: Invasion of the Spider-Slayers'),
('NES_00C58C72', 'Megaman'),
('NES_00DB4876', 'Ghosts''n Goblins'),
('NES_01182D01', 'The Legend of Zelda'),
('NES_004067E5', 'Super Mario Bros.'),
('NES_00D98C89', 'Contra'),
('NES_00E81975', 'Castlevania'),
('NES_02A4E5C6', 'Super Mario Bros. 3'),
('NES_020CBE3A', 'Super Mario Bros. 2'),
('NES_04E4CC1C', 'Kirby''s Adventure'),
('NES_01791A4C', 'Battletoads'),
('NES_00287FC2', 'Donkey Kong'),
('NES_0066267B', 'Dr. Mario'),
('NES_00234B4D', 'Donkey Kong 3'),
('NES_0023DD9E', 'Space Invaders'),
('NES_0028E9AD', 'Excitebike'),
('NES_00601F2F', 'Galaga'),
('NES_00BD97A2', 'Metroid'),
('NES_00C72D76', 'Duck Tales'),
('NES_0124CE1A', 'Ultima: Warriors of Destiny'),
('NES_0134557B', 'Ultima: Quest of the Avatar'),
('NES_016E2DF1', 'Bubble Bobble Part 2'),
('NES_016F0F72', 'Ultima: Exodus'),
('NES_01827ADC', 'Tiny Toon Adventures'),
('NES_01AE992C', 'Bubble Bobble'),
('NES_01BE7B6B', 'Megaman II'),
('NES_01FF771C', 'Megaman III'),
('NES_02B98DB7', 'Megaman IV'),
('NES_02D8460A', 'Megaman V'),
('NES_030FF49A', 'Megaman VI'),
('NES_00265E49', 'Donkey Kong Jr.'),
('NES_003988F0', 'Xevious'),
('NES_004E838C', 'Donkey Kong Classics'),
('NES_002854FA', 'LJ65'),
('NES_002B3246', 'Sir Ababol'),
('NES_002C1FC2', 'Pac-Man'),
('NES_00421B5A', '1942'),
('NES_0059341A', 'Q*bert'),
('NES_0070D8A9', 'Paperboy'),
('NES_00BC46A6', '1943'),
('NES_00E3274E', 'Tetris'),
('NES_01371B81', 'Paperboy 2'),
('NES_01772072', 'Tetris 2'),
('NES_0178C193', 'Tetris Flash'),
('NES_01809FCF', 'Double Dragon'),
('NES_02DBD993', 'Yoshi'),
('NES_0023E954', 'K.Y.F.F.'),
('NES_002A5639', 'Duck Hunt'),
('NES_00A5177E', 'Super Mario Bros. + Duck Hunt'),
('NES_00BA4E3A', 'A Nightmare on Elm Street'),
('NES_011CDF19', 'Bomberman II'),
('NES_01AECDD5', 'Nintendo World Cup'),
('NES_005D82C4', 'Back to the Future'),
('NES_00617733', 'Karate Kid'),
('NES_00AA7EDA', 'Dragon''s Lair'),
('NES_00C0C2F8', 'Who Framed Roger Rabbit?'),
('NES_0107EFD9', 'Top Gun'),
('NES_014AE977', 'Dr. Jekyll and Mr. Hyde'),
('NES_017B14A6', 'Top Gun: The Second Mission'),
('NES_0181B61B', 'Back to the Future II & III'),
('NES_0191AEDB', 'Toxic Crusaders'),
('NES_019FAC91', 'Teenage Mutant Ninja Turtles'),
('NES_021A75A8', 'Castlevania II: Simon''s Quest'),
('NES_02DB59FD', 'Wario''s Woods'),
('NES_00260203', 'Mario Bros.'),
('NES_00634A85', 'Puzznic'),
('NES_0062BE92', 'Krazy Kreatures'),
('NES_00C27BD5', 'The Guardian Legend'),
('NES_00C474AA', 'Life Force'),
('NES_011B36E5', 'Joe & Mac'),
('NES_014ACF3F', 'Action in New York'),
('NES_01641894', 'Mighty Final Fight'),
('NES_0169F676', 'Bucky O''Hare'),
('NES_016FD484', 'New Ghostbusters II'),
('NES_0172104C', 'Panic Restaurant'),
('NES_01762B98', 'Battle Kid: Fortress of Peril'),
('NES_018206C7', 'Sweet Home'),
('NES_01920020', 'Felix the Cat'),
('NES_01A4A280', 'Super C'),
('NES_01C7AB58', 'Clash at Demon Head'),
('NES_01EFB862', 'Little Samson'),
('NES_01FC762B', 'Metal Storm'),
('NES_020CC47E', 'Zelda II: The Adventure of Link'),
('NES_0048F418', 'Tetris'),
('HTML5_TICTACTOE', 'Tic-Tac-Toe');